topnet:
    nfeat: 8
    nlevels: 6
    code_nfts: 256

encoder:
    emb_dim: 128
    ch_mid: 64
    num_layers: 5
    radius: 0.15

discriminator:
    chs: [2048, 512, 256, 128, 64, 1]

num_points: 2048
cat_name: 'chair'

batch_size: 2
learning_rate: 1e-4
max_epoch: 10
num_workers: 10

caching: False # turning off data cache makes dataloader slower; while turning on will consume large disk space

data:
    fig_dir: figures
    pcd_root: /home/neil/shapenet_kp/release/kpnet/pcds 
    train_txt: /home/neil/shapenet_kp/release/kpnet/splits/train.txt
    val_txt: /home/neil/shapenet_kp/release/kpnet/splits/val.txt 

beta:
    concentration0: 0.05
    concentration1: 0.01

symmetry_factor: 1e-1
recon_factor: 1e1

hydra:
    run:
        dir: outputs/${cat_name}

    sweep:
        dir: multirun
        subdir: ${cat_name}